services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - BASE_API_URL=${BASE_API_URL}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/tmp
    ports:
      - "8080"
    depends_on:
      - db
      - minio
    networks:
      - app-network
    environment:
      # Database Configuration
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      
      # MinIO Configuration  
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-minio:9000}
      
      # Authentication Configuration
      JWT_SECRET: ${JWT_SECRET}
      PASSWORD_PEPPER: ${PASSWORD_PEPPER}
      
      # Admin User Configuration (optional)
      ADMIN_USER: ${ADMIN_USER:-}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
      
      # Input Validation Configuration
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}  # 10MB default
      MAX_REQUEST_BODY_SIZE: ${MAX_REQUEST_BODY_SIZE:-1048576}  # 1MB default
      MAX_FILENAME_LENGTH: ${MAX_FILENAME_LENGTH:-255}
      
      # CORS Configuration
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000}
      
      # Application Configuration
      GIN_MODE: ${GIN_MODE:-debug}
      API_DOMAIN: ${API_DOMAIN:-http://localhost}
      HTTPS_MODE: ${HTTPS_MODE:-false}

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data: